_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 41
                - 51
                - 55
                - 63
            "2":
                - 1
                - 41
                - 51
                - 55
                - 63
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.10
            "5": 0.18.7
            "8":
                - 1
                - 5
            "12": 0.18.7
            "13": linux-x86_64
device:
    value: cuda
epochs:
    value: 200
learning_rate:
    value: 0.001
